version: 2
updates:
#   - package-ecosystem: "npm"
#     directory: "/website"
#     target-branch: "develop"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "maboa"
#     assignees:
#       - "Laurian"
#     labels:
#       - "npm"
#       - "dependencies"
#     allow:
#       - dependency-type: "direct"
#     ignore:
#       - dependency-name: "*"
#         update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/conferences"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    reviewers:
      - "maboa"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

#   - package-ecosystem: "npm"
#     directory: "/packages/remixer"
#     target-branch: "develop"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "maboa"
#       - "Laurian"
#     assignees:
#       - "piotrf"
#     labels:
#       - "npm"
#       - "dependencies"
#     allow:
#       - dependency-type: "direct"
#     ignore:
#       - dependency-name: "*"
#         update-types: ["version-update:semver-major"]

#   - package-ecosystem: "npm"
#     directory: "/packages/storybook"
#     target-branch: "develop"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "Laurian"
#     assignees:
#       - "piotrf"
#     labels:
#       - "npm"
#       - "dependencies"
#     allow:
#       - dependency-type: "direct"
#     ignore:
#       - dependency-name: "*"
#         update-types: ["version-update:semver-major"]

#   - package-ecosystem: "npm"
#     directory: "/packages/common"
#     target-branch: "develop"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "Laurian"
#     assignees:
#       - "piotrf"
#     labels:
#       - "npm"
#       - "dependencies"
#     allow:
#       - dependency-type: "direct"
#     ignore:
#       - dependency-name: "*"
#         update-types: ["version-update:semver-major"]

#   - package-ecosystem: "npm"
#     directory: "/packages/app"
#     target-branch: "develop"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "Laurian"
#     assignees:
#       - "piotrf"
#     labels:
#       - "npm"
#       - "dependencies"
#     allow:
#       - dependency-type: "direct"
#     ignore:
#       - dependency-name: "*"
#         update-types: ["version-update:semver-major"]
