/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f70fed74-666a-41a1-ae62-bdbab6ba6fb1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_N4x6dwTVm",
    "aws_user_pools_web_client_id": "359ncrquiaka0082mf0ivmjqvc",
    "oauth": {}
};


export default awsmobile;
