/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:b2d3f876-17f6-44b3-a9c2-a31ce219a78b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_qRD69m8Kt",
    "aws_user_pools_web_client_id": "mljenqs0mdegstbbka8fujng0",
    "oauth": {},
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_user_files_s3_bucket": "hyperaudio-data",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
